/**
 * ETL/ELT generated-script helpers: pull credentials from the selected
 * DataHive connector at runtime via /api/connectors/{id}/runtime-env.
 */
(function (global) {
  "use strict";

  function apiBase() {
    if (typeof global.etlApiBaseUrl === "function") return global.etlApiBaseUrl();
    if (global.DataHiveHttp && typeof global.DataHiveHttp.apiBase === "function") {
      return global.DataHiveHttp.apiBase();
    }
    var host =
      (global.location && global.location.hostname) || "127.0.0.1";
    return "http://" + host + ":5055";
  }

  /** Constants + apply_connector_runtime / snowflake_connect helpers. */
  function etlPythonRuntimeBootstrapLines(ctx) {
    ctx = ctx || {};
    return [
      "DATAHIVE_API_BASE = " + JSON.stringify(apiBase()),
      "SOURCE_CONNECTOR_ID = " + JSON.stringify(ctx.sourceConnectorId || ""),
      "TARGET_CONNECTOR_ID = " + JSON.stringify(ctx.targetConnectorId || ""),
      "SOURCE_CONNECTOR = " + JSON.stringify(ctx.sourceType || ""),
      "TARGET_CONNECTOR = " + JSON.stringify(ctx.targetType || ""),
      "_DH_TEMP_CRED_FILES: list[str] = []",
      "",
      "",
      "def _http_json(url: str) -> dict[str, Any]:",
      "    import json",
      "    import urllib.error",
      "    import urllib.request",
      "",
      "    req = urllib.request.Request(",
      "        url,",
      "        headers={",
      '            "X-DataHive-User": os.environ.get("DATAHIVE_USER", "etl"),',
      '            "Accept": "application/json",',
      "        },",
      "    )",
      "    try:",
      "        with urllib.request.urlopen(req, timeout=60) as resp:",
      "            return json.loads(resp.read().decode(\"utf-8\"))",
      "    except urllib.error.HTTPError as exc:",
      "        body = exc.read().decode(\"utf-8\", errors=\"replace\")",
      "        raise RuntimeError(",
      '            f\"DataHive runtime-env HTTP {exc.code} for {url}: {body}\"',
      "        ) from exc",
      "",
      "",
      "def apply_connector_runtime(connector_id: str) -> dict[str, Any]:",
      '    """Load the selected connector\'s saved credentials into env / temp files."""',
      "    if not connector_id:",
      "        return {}",
      "    import json",
      "    import tempfile",
      "    from pathlib import Path",
      "",
      "    # Allow offline / CI overrides without calling the API.",
      '    inline = os.environ.get("DATAHIVE_RUNTIME_ENV_JSON", "").strip()',
      "    if inline:",
      "        data = json.loads(inline)",
      "    else:",
      "        base = os.environ.get(\"DATAHIVE_API_BASE\", DATAHIVE_API_BASE).rstrip(\"/\")",
      '        data = _http_json(f\"{base}/api/connectors/{connector_id}/runtime-env\")',
      "    if not data.get(\"ok\"):",
      '        raise RuntimeError(f\"runtime-env failed for connector {connector_id}: {data}\")',
      "    for key, value in (data.get(\"env\") or {}).items():",
      "        if value is None or value == \"\":",
      "            continue",
      "        os.environ[str(key)] = str(value)",
      "    for env_key, content in (data.get(\"files\") or {}).items():",
      "        if content is None or content == \"\":",
      "            continue",
      '        suffix = \".pem\" if \"PRIVATE_KEY\" in str(env_key).upper() else \".json\"',
      '        fd, path = tempfile.mkstemp(prefix=\"datahive_cred_\", suffix=suffix)',
      "        os.close(fd)",
      "        text = content if isinstance(content, str) else json.dumps(content)",
      "        Path(path).write_text(text, encoding=\"utf-8\")",
      "        os.environ[str(env_key)] = path",
      "        _DH_TEMP_CRED_FILES.append(path)",
      "    return data",
      "",
      "",
      "def snowflake_connect(connector_id: str = \"\", **overrides: Any):",
      "    import snowflake.connector",
      "    from cryptography.hazmat.backends import default_backend",
      "    from cryptography.hazmat.primitives import serialization",
      "    from pathlib import Path",
      "",
      "    apply_connector_runtime(connector_id or SOURCE_CONNECTOR_ID or TARGET_CONNECTOR_ID)",
      "    kwargs: dict[str, Any] = {",
      '        \"account\": os.environ.get(\"SNOWFLAKE_ACCOUNT\"),',
      '        \"user\": os.environ.get(\"SNOWFLAKE_USER\"),',
      '        \"password\": os.environ.get(\"SNOWFLAKE_PASSWORD\"),',
      '        \"warehouse\": os.environ.get(\"SNOWFLAKE_WAREHOUSE\"),',
      '        \"database\": os.environ.get(\"SNOWFLAKE_DATABASE\"),',
      '        \"schema\": os.environ.get(\"SNOWFLAKE_SCHEMA\"),',
      '        \"role\": os.environ.get(\"SNOWFLAKE_ROLE\"),',
      "        \"login_timeout\": 30,",
      "        \"network_timeout\": 45,",
      "    }",
      '    auth = (os.environ.get(\"SNOWFLAKE_AUTHENTICATOR\") or \"\").lower()',
      '    if auth == \"oauth\" and os.environ.get(\"SNOWFLAKE_TOKEN\"):',
      '        kwargs[\"authenticator\"] = \"oauth\"',
      '        kwargs[\"token\"] = os.environ[\"SNOWFLAKE_TOKEN\"]',
      '        kwargs.pop(\"user\", None)',
      '        kwargs.pop(\"password\", None)',
      '    pk_path = os.environ.get(\"SNOWFLAKE_PRIVATE_KEY_PATH\")',
      "    if pk_path:",
      "        pem = Path(pk_path).read_bytes()",
      '        passphrase = os.environ.get(\"SNOWFLAKE_PRIVATE_KEY_PASSPHRASE\")',
      "        key = serialization.load_pem_private_key(",
      "            pem,",
      "            password=passphrase.encode(\"utf-8\") if passphrase else None,",
      "            backend=default_backend(),",
      "        )",
      "        kwargs[\"private_key\"] = key.private_bytes(",
      "            encoding=serialization.Encoding.DER,",
      "            format=serialization.PrivateFormat.PKCS8,",
      "            encryption_algorithm=serialization.NoEncryption(),",
      "        )",
      '        kwargs.pop(\"password\", None)',
      "    kwargs.update({k: v for k, v in overrides.items() if v is not None})",
      "    clean = {k: v for k, v in kwargs.items() if v is not None and v != \"\"}",
      '    if not clean.get(\"account\"):',
      '        raise RuntimeError(\"Snowflake account missing — select a saved Snowflake connector.\")',
      "    return snowflake.connector.connect(**clean)",
      "",
      "",
      "def aws_boto3_session():",
      "    import boto3",
      "",
      "    apply_connector_runtime(",
      "        SOURCE_CONNECTOR_ID",
      '        if SOURCE_CONNECTOR == \"aws\"',
      "        else TARGET_CONNECTOR_ID",
      "        if TARGET_CONNECTOR == \"aws\"",
      "        else SOURCE_CONNECTOR_ID or TARGET_CONNECTOR_ID",
      "    )",
      '    region = os.environ.get(\"AWS_DEFAULT_REGION\") or os.environ.get(\"AWS_REGION\") or \"us-east-1\"',
      "    session = boto3.Session(",
      '        aws_access_key_id=os.environ.get(\"AWS_ACCESS_KEY_ID\") or None,',
      '        aws_secret_access_key=os.environ.get(\"AWS_SECRET_ACCESS_KEY\") or None,',
      "        region_name=region,",
      "    )",
      '    role_arn = os.environ.get(\"AWS_ROLE_ARN\")',
      "    if role_arn:",
      "        sts = session.client(\"sts\")",
      "        assumed = sts.assume_role(",
      "            RoleArn=role_arn,",
      '            RoleSessionName=os.environ.get(\"AWS_ROLE_SESSION_NAME\", \"datahive-etl\"),',
      "        )",
      "        creds = assumed[\"Credentials\"]",
      "        session = boto3.Session(",
      '            aws_access_key_id=creds[\"AccessKeyId\"],',
      '            aws_secret_access_key=creds[\"SecretAccessKey\"],',
      '            aws_session_token=creds[\"SessionToken\"],',
      "            region_name=region,",
      "        )",
      "    return session",
      "",
      "",
      "def azure_credential():",
      "    from azure.identity import ClientSecretCredential",
      "",
      "    apply_connector_runtime(",
      "        SOURCE_CONNECTOR_ID",
      '        if SOURCE_CONNECTOR == \"azure\"',
      "        else TARGET_CONNECTOR_ID",
      "        if TARGET_CONNECTOR == \"azure\"",
      "        else SOURCE_CONNECTOR_ID or TARGET_CONNECTOR_ID",
      "    )",
      "    tenant = os.environ.get(\"AZURE_TENANT_ID\")",
      "    client_id = os.environ.get(\"AZURE_CLIENT_ID\")",
      "    secret = os.environ.get(\"AZURE_CLIENT_SECRET\")",
      "    if not tenant or not client_id or not secret:",
      '        raise RuntimeError(\"Azure connector credentials incomplete (tenant/client/secret).\")',
      "    return ClientSecretCredential(tenant, client_id, secret)",
      "",
      "",
      "def ensure_gcp_credentials(connector_id: str = \"\") -> None:",
      "    apply_connector_runtime(connector_id or SOURCE_CONNECTOR_ID or TARGET_CONNECTOR_ID)",
      "",
    ];
  }

  /** Shared pandas read/write using applied connector credentials. */
  function etlPythonCloudIoLines() {
    return [
      "def _parse_s3_uri(uri: str) -> tuple[str, str]:",
      "    import re",
      "",
      '    m = re.match(r\"^s3://([^/]+)/?(.*)$\", uri.strip())',
      "    if not m:",
      '        raise ValueError(f\"Expected s3://bucket/path, got: {uri}\")',
      "    return m.group(1), m.group(2)",
      "",
      "",
      "def _parse_gs_uri(uri: str) -> tuple[str, str]:",
      "    import re",
      "",
      '    m = re.match(r\"^gs://([^/]+)/?(.*)$\", uri.strip())',
      "    if not m:",
      '        raise ValueError(f\"Expected gs://bucket/path, got: {uri}\")',
      "    return m.group(1), m.group(2)",
      "",
      "",
      "def _parse_abfs_uri(uri: str) -> tuple[str, str, str]:",
      "    import re",
      "",
      "    m = re.match(",
      '        r\"^(?:abfss?|wasbs?)://([^@]+)@([^.]+)[^/]*/?(.*)$\",',
      "        uri.strip(),",
      "        re.I,",
      "    )",
      "    if not m:",
      '        raise ValueError(f\"Expected abfss://container@account…/path, got: {uri}\")',
      "    return m.group(1), m.group(2), m.group(3)",
      "",
      "",
      "def read_cloud_source(source_object: str, connector: str, connector_id: str) -> pd.DataFrame:",
      "    obj = (source_object or \"\").strip()",
      "    cloud = (connector or \"\").lower()",
      '    if cloud in {\"gcp\", \"googlecloud\"} or obj.startswith(\"gs://\"):',
      "        ensure_gcp_credentials(connector_id)",
      "        if obj.startswith(\"gs://\"):",
      "            from google.cloud import storage",
      "            import tempfile",
      "            from pathlib import Path",
      "",
      "            bucket_name, prefix = _parse_gs_uri(obj)",
      "            client = storage.Client()",
      "            blob = client.bucket(bucket_name).blob(prefix)",
      "            with tempfile.TemporaryDirectory(prefix=\"datahive_gcs_\") as tmp:",
      "                local = Path(tmp) / (Path(prefix).name or \"object\")",
      "                blob.download_to_filename(local.as_posix())",
      "                return _read_local_tabular(local)",
      "        import pandas_gbq",
      "",
      "        project = obj.split(\".\", 1)[0]",
      '        sql = f\"SELECT * FROM `{obj}`\"',
      "        return pandas_gbq.read_gbq(sql, project_id=project)",
      '    if cloud == \"aws\" or obj.startswith(\"s3://\"):',
      "        apply_connector_runtime(connector_id)",
      "        session = aws_boto3_session()",
      "        bucket, key = _parse_s3_uri(obj)",
      "        import tempfile",
      "        from pathlib import Path",
      "",
      "        s3 = session.client(\"s3\")",
      "        with tempfile.TemporaryDirectory(prefix=\"datahive_s3_\") as tmp:",
      "            local = Path(tmp) / (Path(key).name or \"object\")",
      "            s3.download_file(bucket, key, local.as_posix())",
      "            return _read_local_tabular(local)",
      '    if cloud == \"azure\" or obj.lower().startswith((\"abfs://\", \"abfss://\", \"wasb://\", \"wasbs://\")):',
      "        from azure.storage.filedatalake import DataLakeServiceClient",
      "        import tempfile",
      "        from pathlib import Path",
      "",
      "        cred = azure_credential()",
      "        container, account, path = _parse_abfs_uri(obj)",
      '        svc = DataLakeServiceClient(account_url=f\"https://{account}.dfs.core.windows.net\", credential=cred)',
      "        file_client = svc.get_file_system_client(container).get_file_client(path)",
      "        with tempfile.TemporaryDirectory(prefix=\"datahive_adls_\") as tmp:",
      "            local = Path(tmp) / (Path(path).name or \"object\")",
      "            with open(local, \"wb\") as fh:",
      "                downloader = file_client.download_file()",
      "                downloader.readinto(fh)",
      "            return _read_local_tabular(local)",
      '    if cloud == \"snowflake\":',
      "        conn = snowflake_connect(connector_id)",
      "        try:",
      '            return pd.read_sql(f\"SELECT * FROM {obj}\", conn)',
      "        finally:",
      "            conn.close()",
      '    if cloud in {\"postgres\", \"postgresql\"}:',
      "        apply_connector_runtime(connector_id)",
      "        from sqlalchemy import create_engine",
      "",
      '        engine = create_engine(os.environ[\"POSTGRES_CONNINFO\"])',
      '        return pd.read_sql(f\"SELECT * FROM {obj}\", engine)',
      '    raise NotImplementedError(f\"No read path for connector={connector!r} object={obj!r}\")',
      "",
      "",
      "def write_cloud_target(df: pd.DataFrame, target_object: str, connector: str, connector_id: str) -> None:",
      "    obj = (target_object or \"\").strip()",
      "    cloud = (connector or \"\").lower()",
      '    if cloud in {\"gcp\", \"googlecloud\"} or obj.startswith(\"gs://\"):',
      "        ensure_gcp_credentials(connector_id)",
      "        if obj.startswith(\"gs://\"):",
      "            from google.cloud import storage",
      "            import tempfile",
      "            from pathlib import Path",
      "",
      '            out = obj.rstrip(\"/\") + (\"\" if obj.lower().endswith((\".parquet\", \".csv\")) else \"/data.parquet\")',
      "            bucket_name, prefix = _parse_gs_uri(out)",
      "            with tempfile.TemporaryDirectory(prefix=\"datahive_out_\") as tmp:",
      "                local = Path(tmp) / Path(prefix).name",
      '                if out.lower().endswith(\".csv\"):',
      "                    df.to_csv(local, index=False)",
      "                else:",
      "                    df.to_parquet(local, index=False)",
      "                storage.Client().bucket(bucket_name).blob(prefix).upload_from_filename(",
      "                    local.as_posix()",
      "                )",
      '            print(f\"Wrote {len(df)} rows to {out}\")',
      "            return",
      "        import pandas_gbq",
      "",
      "        project, dataset, table = obj.split(\".\", 2)",
      "        pandas_gbq.to_gbq(",
      "            df,",
      '            destination_table=f\"{dataset}.{table}\",',
      "            project_id=project,",
      '            if_exists=\"replace\",',
      "        )",
      '        print(f\"Wrote {len(df)} rows to BigQuery {obj}\")',
      "        return",
      '    if cloud == \"aws\" or obj.startswith(\"s3://\"):',
      "        session = aws_boto3_session()",
      '        out = obj.rstrip(\"/\") + (\"\" if obj.lower().endswith((\".parquet\", \".csv\")) else \"/data.parquet\")',
      "        bucket, key = _parse_s3_uri(out)",
      "        import tempfile",
      "        from pathlib import Path",
      "",
      "        with tempfile.TemporaryDirectory(prefix=\"datahive_s3out_\") as tmp:",
      "            local = Path(tmp) / Path(key).name",
      '            if out.lower().endswith(\".csv\"):',
      "                df.to_csv(local, index=False)",
      "            else:",
      "                df.to_parquet(local, index=False)",
      "            session.client(\"s3\").upload_file(local.as_posix(), bucket, key)",
      '        print(f\"Wrote {len(df)} rows to {out}\")',
      "        return",
      '    if cloud == \"azure\" or obj.lower().startswith((\"abfs://\", \"abfss://\")):',
      "        from azure.storage.filedatalake import DataLakeServiceClient",
      "        import tempfile",
      "        from pathlib import Path",
      "",
      "        cred = azure_credential()",
      '        out = obj.rstrip(\"/\") + (\"\" if Path(obj).suffix else \"/data.parquet\")',
      "        container, account, path = _parse_abfs_uri(out)",
      '        svc = DataLakeServiceClient(account_url=f\"https://{account}.dfs.core.windows.net\", credential=cred)',
      "        file_client = svc.get_file_system_client(container).get_file_client(path)",
      "        with tempfile.TemporaryDirectory(prefix=\"datahive_adlsout_\") as tmp:",
      "            local = Path(tmp) / Path(path).name",
      "            df.to_parquet(local, index=False)",
      "            with open(local, \"rb\") as fh:",
      "                file_client.upload_data(fh, overwrite=True)",
      '        print(f\"Wrote {len(df)} rows to {out}\")',
      "        return",
      '    if cloud == \"snowflake\":',
      "        from snowflake.connector.pandas_tools import write_pandas",
      "",
      "        parts = obj.split(\".\")",
      '        database = parts[0] if len(parts) >= 3 else os.environ.get(\"SNOWFLAKE_DATABASE\", \"SALES_DB\")',
      '        schema = parts[-2] if len(parts) >= 2 else os.environ.get(\"SNOWFLAKE_SCHEMA\", \"RAW\")',
      "        table = parts[-1]",
      "        conn = snowflake_connect(connector_id, database=database, schema=schema)",
      "        try:",
      "            write_pandas(",
      "                conn,",
      "                df,",
      "                table_name=table,",
      "                database=database,",
      "                schema=schema,",
      "                auto_create_table=True,",
      "                overwrite=True,",
      "                quote_identifiers=False,",
      "            )",
      '            print(f\"Wrote {len(df)} rows to Snowflake {database}.{schema}.{table}\")',
      "        finally:",
      "            conn.close()",
      "        return",
      '    if cloud in {\"postgres\", \"postgresql\"}:',
      "        apply_connector_runtime(connector_id)",
      "        from sqlalchemy import create_engine",
      "",
      '        engine = create_engine(os.environ[\"POSTGRES_CONNINFO\"])',
      '        df.to_sql(obj, engine, if_exists=\"replace\", index=False)',
      '        print(f\"Wrote {len(df)} rows to Postgres {obj}\")',
      "        return",
      '    raise NotImplementedError(f\"No write path for connector={connector!r} object={obj!r}\")',
      "",
      "",
      "def _read_local_tabular(path: Path) -> pd.DataFrame:",
      "    suffix = path.suffix.lower()",
      '    if suffix == \".parquet\":',
      "        return pd.read_parquet(path)",
      '    if suffix in {\".xlsx\", \".xls\"}:',
      "        return pd.read_excel(path)",
      '    if suffix == \".tsv\":',
      "        return pd.read_csv(path, sep=\"\\t\")",
      '    if suffix in {\".json\", \".jsonl\", \".ndjson\"}:',
      "        import json",
      "",
      '        text = path.read_text(encoding=\"utf-8\").strip()',
      "        if not text:",
      "            return pd.DataFrame()",
      '        if \"\\n\" in text and not text.lstrip().startswith(\"[\"):',
      "            rows = [json.loads(line) for line in text.splitlines() if line.strip()]",
      "            return pd.json_normalize(rows, sep=\"__\")",
      "        payload = json.loads(text)",
      "        if isinstance(payload, list):",
      "            return pd.json_normalize(payload, sep=\"__\")",
      "        return pd.json_normalize([payload], sep=\"__\")",
      "    return pd.read_csv(path)",
      "",
    ];
  }

  global.etlPythonRuntimeBootstrapLines = etlPythonRuntimeBootstrapLines;
  global.etlPythonCloudIoLines = etlPythonCloudIoLines;
})(typeof window !== "undefined" ? window : globalThis);
